Pretend to be on macOS instead of Windows
Workaround for AttributeError: 'NoneType' object has no attribute 'NeedCurrentDirectoryForExePath' when calling`_winapi.NeedCurrentDirectoryForExePath`, where `_winapi` is None on UNIX. See https://github.com/GenericMappingTools/pygmt/pull/2711#issuecomment-1778456261