Add back rioxarray import and ImportError check to tilemap.py
Partially revert a77392909c9fd8ee44da78ace44267a2f39288de to fix `AttributeError: 'DataArray' object has no attribute 'rio'` in `pygmt/src/tilemap.py`, because the reproject from EPSG:3857 to OGC:CRS84 step requires it.