Load GMTDataArray accessor information at xr.Dataset level
Need to load the gmt accessor at the xr.Dataset level instead of the xr.DataArray level, otherwise the info gets lost at the `.to_dataset()` call. Had to add the `@xr.register_dataset_accessor("gmt")` decorator on `class GMTDataArrayAccessort` to prevent `AttributeError: 'Dataset' object has no attribute 'gmt'`.